config/routes.rb
Rails.application.routes.draw do
  root 'landing#home'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destory]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :password_changes, only: [:new, :create, :edit, :update]
  resources :projects, only: [:index, :new, :create, :show, :destroy] do
    resources :suggests, only: [:new, :create, :show, :edit, :update, :destroy]
  end
  resources :comments, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :accept_suggests, only: [:create, :show]
  resources :reviews, only: [:index, :new, :create, :show, :edit, :update]
  resources :email_changes, only: [:edit, :update]
end

app/models/suggest.rb
class Suggest < ApplicationRecord
  PHOTOS_MAXIMUM = 5

  belongs_to :user
  belongs_to :project

  has_many :photos, as: :photable, inverse_of: :photable, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :accept_suggest, foreign_key: 'approval_suggest_id', dependent: :destroy
  has_one :recommending_user, through: :accept_suggest, source: :user
  has_one :review, foreign_key: 'suggest_id'

  accepts_nested_attributes_for :photos, allow_destroy: true

  validates :user_id, presence: true
  validates :project_id, presence: true
  validates :title, length: { maximum: 50 }, presence: true
  validates :content, presence: true
  validates :estimated_amount, numericality: { only_integer: true }, length: { maximum: 10 }, presence: true
  validates :photos, length: { maximum: 5 }
end

app/controllers/suggests_controller.rb
class SuggestsController < ApplicationController
  include Shared::SuggestSupport

  before_action :logged_in_user
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :builder_can_suggest, only: [:new, :create]
  before_action :builder_cant_suggest_twise, only: [:new, :create]

  def new
    redirect_to root_url and return if @project.nil?
    @suggest = current_user.suggests.build
    @suggest.photos.build
  end

  def create
    @suggest = Suggest.new(suggest_params)
    if @suggest.save
      redirect_to project_suggest_url(@suggest.project.id, @suggest.id)
    else
      flash.now[:warning] = "提案の投稿に失敗しました。"
      render 'new'
    end
  end

  def show
    @suggest = Suggest.find_by(id: params[:id])
    redirect_to root_url and return if @suggest.nil?
    @project = @suggest.project
    @customer = @project.user
    @comment = Comment.new
    @comments = @suggest.comments.paginate(page: params[:page], per_page: 10)
  end

  def edit
    @suggest = Suggest.find_by(id: params[:id])
    @suggest.photos.build if @suggest.photos.blank?
  end

  def update
    @suggest = Suggest.find(params[:id])
    if @suggest.update(update_params)
      redirect_to project_suggest_path(@suggest.project, @suggest)
    else
      flash.now[:warning] = "提案の編集に失敗しました。"
      render 'edit'
    end
  end

  def destroy
    @suggest.destroy
    flash[:success] = "提案が削除されました。"
    redirect_to project_url(params[:project_id])
  end

  private

  def suggest_params
    params.require(:suggest).permit(:title,
                                    :content,
                                    :estimated_amount,
                                    :project_id,
                                    photos_attributes: [:image]).merge(user_id: current_user.id)
  end

  def update_params
    params.require(:suggest).permit(:content,
                                    :estimated_amount,
                                    photos_attributes: [:image, :id, :_destroy])
  end

  def correct_user
    @suggest = current_user.suggests.find_by(id: params[:id])
    if @suggest.nil?
      flash.now[:warning] = "指定されたプロジェクトは見つかりませんでした。"
      redirect_to root_url
    end
  end

  def builder_can_suggest
    unless current_user.builder?
      redirect_to current_user
      flash.now[:warning] = "提案を作成できるのはビルダーだけです。"
    end
  end

  def builder_cant_suggest_twise
    @project = Project.find_by(id: params[:project_id]) or Project.find_by(id: params[:suggest][:project_id])
    if builder_already_suggest?(@project)
      redirect_to @project || root_url
      flash[:warning] = "同じプロジェクトへの提案はできません。"
    end
  end
end

app/views/suggests/edit.html.erb
<% provide(:title, "#{@suggest.title}を編集する") %>
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 white-box">
        <h2 class="gray-bottom-line"><%= @suggest.project.name %>に対する提案を編集します。</h2>
        <%= render 'shared/flash' %>
        <%= render 'shared/error_messages', object: @suggest %>
        <div>
          <%= form_with(model: [@suggest.project, @suggest], local: true) do |f| %>
            <div class="preview-field flex">
              <% if @suggest.photos.first.image.present? %>
                <% @suggest.photos.each_with_index do |photo, index| %>
                  <div class="preview-box" id="preview-box_<%= index %>">
                    <div class="upper-box">
                      <%= image_tag photo.image.url, alt: "preview" %>
                    </div>
                    <div class="lower-box">
                      <label class="update-box" id="edit_btn_<%= index %>">
                        <span>編集</span>
                      </label>
                      <div class="delete-box" id="delete_btn_<%= index %>">
                        <span>削除</span>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
              <div id="label-field">
                <%= f.label :"photos_attributes_#{@suggest.photos.size}_image", class: "photo-label", id: "photo-label-0" do %>
                  <p>クリックして画像をアップロード(最大5枚)</p>
                <% end %>
              </div>
              <div class="input-space">
                <%= f.fields_for :photos do |photo| %>
                  <%= photo.file_field :image, class: "hidden-field" %>
                  <%= photo.check_box :_destroy, class: "hidden-field", checked: "#{'checked' if photo.object.image.blank?}" %>
                <% end %>
                <% @suggest.photos.size.upto(4).each do |i| %>
                  <input name="suggest[photos_attributes][<%= i %>][image]" id="suggest_photos_attributes_<%= i %>_image" class="hidden-field" type="file">
                <% end %>
              </div>
            </div>
            <%= f.label :estimated_amount, class: "suggest-info" %>
            <%= f.text_field :estimated_amount, placefolder: @suggest.estimated_amount, class: "form-control" %>
            <%= f.label :content, class: "suggest-info" %>
            <%= f.text_area :content, placefolder: @suggest.content, class: "form-control" %>
            <div class="flex justify-content-center">
              <%= f.submit "提案を編集する", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/suggests/new.html.erb
<% provide :title, "#{@project.name}へ提案する" %>
<main>
  <div class="container">
    <div class = "row">
      <div class = "col-sm-12">
        <%= link_to "プロジェクトに戻る", project_path(@project), class: "back-link" %>
        <div class="white-box">
          <h2 class="gray-bottom-line">これは<%= @project.name %>に対する提案です。</h2>
          <%= render 'shared/flash' %>
          <%= render 'shared/error_messages', object: @suggest %>
          <div>
            <%= form_with(model: [@project, @suggest], local: true) do |f| %>
              <div class="preview-field flex">
                <div id="label-field">
                  <%= f.label :"photos_attributes_0_image", class: "photo-label", id: "photo-label-0" do %>
                    <p>クリックして画像をアップロード(最大5枚)</p>
                  <% end %>
                </div>
              </div>
              <%= f.fields_for :photos do |photo| %>
                <%= render 'shared/photo_upload', { model_name: "suggest", photo: photo } %>
              <% end %>
              <%= f.hidden_field :project_id, value: @project.id %>
              <%= f.label :title %>
              <%= f.text_field :title, class: "form-control" %>
              <%= f.label :estimated_amount %>
              <%= f.text_field :estimated_amount, class: "form-control", data: { autonumeric: { mDec: 0 } } %>
              <%= f.label :content %>
              <%= f.text_area :content, class: "form-control" %>
              <%= f.submit "提案する", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/suggests/show.html.erb
<% provide :title, "#{@project.name}への提案" %>
<main>
  <div class="container">
    <%= link_to "プロジェクトに戻る", project_path(@project), class: "back-link" %>
    <div class = "row white-box">
      <div class = "col-sm-12">
        <h2 class="gray-bottom-line"><%= @suggest.title %></h2>
        <% if @suggest.photos.present? %>
          <ul class="show-photo-field">
            <% @suggest.photos.each do |photo| %>
              <li class="show-photo-box"><%= image_tag photo.image.url %></li>
            <% end %>
          </ul>
        <% end %>
        <ul>
          <li class="suggest-info"><span class="font-weight-bold">提案者：</span><%= link_to @suggest.user.name, user_path(@suggest.user) %></li>
          <% if current_user.favorite_suggest?(@suggest) %>
            <li class="suggest-info"><span class="font-weight-bold">提案者連絡先：</span><%= @suggest.user.email %></li>
          <% end %>
          <li class="suggest-info"><span class="font-weight-bold">お見積もり金額(概算)：</span><%= "#{@suggest.estimated_amount.to_s(:delimited)}円" %></li>
          <li class="suggest-info">
            <span class="font-weight-bold">提案内容</span><br>
            <%= safe_join(@suggest.content.split("\n"),tag(:br)) %>
          </li>
        </ul>
        <div class="flex suggest-btn-box">
          <% if current_user?(@suggest.user) %>
            <%= link_to "提案を取り下げる", project_suggest_path(@project, @suggest), method: :delete,
                                                  data: { confirm: "本当に提案を取り下げてもよろしいですか？" },
                                                  class: "btn btn-danger suggest-deletebtn" %>
            <%= link_to "提案を編集する", edit_project_suggest_path(@project, @suggest), class: "btn btn-warning" %>
          <% elsif current_user?(@customer) && !@customer.favorite_suggest?(@suggest) %>
            <%= form_with(model: current_user.accept_suggests.build, local: true) do |f| %>
              <%= hidden_field_tag :suggest_id, @suggest.id %>
              <%= f.submit "提案を受け入れる", class: "btn btn-primary" %>
            <% end %>
          <% elsif current_user?(@customer) && @customer.favorite_suggest?(@suggest) && !@customer.already_review?(@suggest) %>
            <%= link_to "このビルダーを評価する", new_review_path(params: { review: { suggest_id: @suggest.id } }), class: "btn btn-warning" %>
          <% elsif @customer.already_review?(@suggest) %>
            <%= link_to "この提案へのレビューを確認する", review_path(@suggest), class: "btn btn-secondary" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class = "row white-box">
      <div class = "col-sm-12">
        <h3 class="gray-bottom-line"><%= @comments.size %>件のコメント</h3>
        <%= render 'shared/flash' %>
        <% if @comments.any? %>
          <%= render 'comments/comments', comments: @comments %>
        <% else %>
          <p>まだコメントはありません。</p>
        <% end %>
        <div class="comment-form-box">
          <%= form_with(model: @comment, local: true) do |f| %>
            <%= f.hidden_field :suggest_id, value: @suggest.id %>
            <%= f.text_area :content, class: "form-control" %>
            <%= f.submit "コメントを投稿する", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>