config/routes.rb
Rails.application.routes.draw do
  root 'landing#home'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destory]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :password_changes, only: [:new, :create, :edit, :update]
  resources :projects, only: [:index, :new, :create, :show, :destroy] do
    resources :suggests, only: [:new, :create, :show, :edit, :update, :destroy]
  end
  resources :comments, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :accept_suggests, only: [:create, :show]
  resources :reviews, only: [:index, :new, :create, :show, :edit, :update]
  resources :email_changes, only: [:edit, :update]
end

app/controllers/password_changes_controller.rb
class PasswordChangesController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update]
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user?, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by(id: params[:id])
    if @user.present?
      @user.create_change_digest
      UserMailer.password_change(@user).deliver_now
      flash[:info] = "パスワードを変更するためのメールが送信されました。"
      redirect_to @user || root_url
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash.now[:success] = "パスワードが変更されました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def get_user
    @user = User.find_by(email: params[:email])
  end

  def valid_user?
    if !(@user && @user.authenticated?(:change, params[:id]))
      flash[:warning] = "ユーザーが見つかりません"
      redirect_to root_url
    end
  end

  def check_expiration
    if @user.digest_expired?(:change)
      flash[:warning] = "リンクの有効期限が切れています。もう一度はじめからやり直してください。"
      redirect_to new_password_change_url
    end
  end
end

app/views/password_changes/edit.html.erb
<% provide(:title, "パスワードを変更") %>
<main>
  <div class="container">
    <div class = "row justify-content-center">
      <div class = "col-md-6 col-sm-12 white-box">
        <h2 class="text-center pass-change">パスワードを変更する</h2>
        <%= render 'shared/error_messages', object: @user %>
        <%= render 'shared/flash' %>
        <p class="color-orange">新しいパスワードを入力してください。</p>
        <div class = "form">
          <%= form_with(model: @user, url: password_change_path(params[:id]), local: true) do |f| %>
            <%= hidden_field_tag :email, @user.email %>
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control" %>
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
            <%= f.submit "パスワードを変更",class: "btn btn-primary wide-btn" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/password_changes/new.html.erb
<main>
  <div class="container">
    <div class = "row justify-content-center">
      <div class = "col-md-6　col-sm-12">
        <%= link_to "ユーザー編集画面に戻る", edit_user_path(current_user), class: "back-link" %>
        <div class="white-box">
          <h2 class="text-center pass-change">パスワードの変更</h2>
          <p class="color-orange">パスワード再設定用メールを送信します。<br>
          メールに記載されているリンクから、パスワードの再設定を行ってください。
          </p>
          <table class="orange-table">
            <tr>
              <th class="orange-cell">登録されているメールアドレス</th>
            </tr>
            <tr>
              <td class="orange-cell"><%= current_user.email %></td>
            </tr>
          </table>
          <div class="text-center">
          <%= link_to "パスワード再設定用メールを送信する", password_changes_path(params: {id: current_user.id}),
                      method: :post, class:"btn btn-primary"%>
        </div>
      </div>
    </div>
  </div>
</main>