config/routes.rb
Rails.application.routes.draw do
  root 'landing#home'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destory]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :password_changes, only: [:new, :create, :edit, :update]
  resources :projects, only: [:index, :new, :create, :show, :destroy] do
    resources :suggests, only: [:new, :create, :show, :edit, :update, :destroy]
  end
  resources :comments, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :accept_suggests, only: [:create, :show]
  resources :reviews, only: [:index, :new, :create, :show, :edit, :update]
  resources :email_changes, only: [:edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token, :change_token

  before_create :create_activation_digest

  has_many :projects, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :comments, dependent: :destroy
  has_many :suggests, dependent: :destroy
  has_many :accept_suggests, foreign_key: 'user_id', dependent: :destroy
  has_many :approve_suggests, through: :accept_suggests, source: :approval_suggest
  has_many :reviews, foreign_key: 'customer_id'
  has_many :evaluations, class_name: 'Review', foreign_key: 'builder_id', dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  validates :name, presence: true, length: { maximum: 50 }
  validates :email,
            length: { maximum: 100 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false },
            presence: true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :website, format: { with: /\A#{URI.regexp(%w(http https))}\z/ }, allow_blank: true
  validates :intro, length: { maximum: 150 }

  mount_uploader :avatar, AvatarUploader

  has_secure_password

  class << self
    def digest(string)
      if ActiveModel::SecurePassword.min_cost
        cost = BCrypt::Engine::MIN_COST
      else
        cost = BCrypt::Engine.cost
      end
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def create_remember_token
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def delete_remember_token
    update_attribute(:remember_digest, nil)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def create_change_digest
    self.change_token = User.new_token
    update_attribute(:change_digest, User.digest(change_token))
    update_attribute(:change_sent_at, Time.zone.now)
  end

  def digest_expired?(attribute)
    send("#{attribute}_sent_at") < 2.hours.ago
  end

  def follow(user)
    following << user
  end

  def following?(user)
    following.include?(user)
  end

  def favorite_suggest(suggest)
    approve_suggests << suggest
  end

  def favorite_suggest?(suggest)
    approve_suggests.include?(suggest)
  end

  def already_review?(suggest)
    reviews.include? suggest.review
  end

  private

  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy, :following, :followers]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.account_activation(@user).deliver_now
      flash[:info] = "認証メールを送信いたしました。アカウント認証後にサービスをご利用いただけます。"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    if @user.builder?
      @projects = Project.where(id: @user.suggests.map(&:project_id)).
        includes(:user).
        paginate(page: params[:page], per_page: 5)
      @star = @user.evaluations
    else
      @projects = @user.projects.paginate(page: params[:page], per_page: 5)
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(edit_user_params)
      flash[:success] = "ユーザーの情報が更新されました。"
      redirect_to edit_user_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    log_out current_user if logged_in?
    flash.now[:success] = "アカウントを削除しました"
    redirect_to root_url
  end

  def following
    @title = "フォロー中"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page], per_page: 10)
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page], per_page: 10)
    render 'show_follow'
  end

  private

  def user_params
    params.require(:user).permit(:name,
                                 :email,
                                 :password,
                                 :password_confirmation,
                                 :builder)
  end

  def edit_user_params
    params.require(:user).permit(:name,
                                 :avatar,
                                 :website,
                                 :intro)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_url unless current_user?(@user)
  end
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
  <%= hidden_field_tag :followed_id, user.id %>
  <%= f.submit "フォローする", class: "btn btn-primary follow-btn" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id),
            html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "フォローを解除", class: "btn btn-secondary follow-btn" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "プロフィールを編集")%>
<% @user.reload %>
<main>
  <div class="container">
    <div class = "row justify-content-center">
      <div class="col-md-9 col-sm-12 white-box">
        <%= render 'shared/flash' %>
        <%= render 'shared/error_messages', object: @user %>
        <%= form_with model: @user, local: true do |f| %>
          <div class="user-edit-box">
            <% if @user.avatar? %>
              <div class="edit-avatar"><%= render 'shared/avatar', avatar: @user.avatar %></div>
            <% end %>
            <div>
              <div class="edit-username"><%= @user.name %></div>
              <div class="flex">
                <%= link_to "パスワードを変更する", new_password_change_path, class: "btn gray-btn" %>
                <%= link_to "Eメールアドレスを変更する", edit_email_change_path(@user), class: "btn gray-btn to-emailchange" %>
              </div>
              <%= f.file_field :avatar %>
            </div>
          </div>
          <div class = "form">
            <div class="user-editpage-email">
              <div>メールアドレス</div>
              <p><%= @user.email %></p>
            </div>
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
            <% if @user.builder? %>
              <%= f.label :website %>
              <%= f.text_field :website, placeholder: "http://example.com", class: "form-control" %>
              <%= f.label :intro, "会社概要" %>
            <% else %>
              <%= f.label :intro, "プロフィール" %>
            <% end %>
            <%= f.text_area :intro, class: "form-control" %>
            <div class="editbtn-position">
              <%= f.submit "更新する",class: "btn btn-primary edit-btn" %>
                <%= link_to "アカウントの削除", @user, method: :delete,
                                        data: { confirm: "本当に削除してもよろしいですか？" },
                                        class: "btn btn-danger edit-deletebtn" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/new.html.erb
<% provide :title, "ユーザー登録" %>
<main>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6 col-sm-12">
        <div class="white-box">
          <h2 class="text-center">Sign up form</h2>
          <%= render 'shared/error_messages', object: @user %>
          <div class="form">
            <%= form_with model: @user, local: true do |f| %>
              <%= f.label :builder, "カスタマーかビルダーどちらか選んでください" %>
              <div class="flex builder-field">
                <div><%= f.radio_button :builder, :false %><span>家を建てたい</span><br><span>（カスタマー）</span></div>
                <div><%= f.radio_button :builder, :true %><span>家づくりを提案したい</span><br><span>（ビルダー）</span></div>
              </div>
              <%= f.label :name %>
              <%= f.text_field :name, placeholder: "フルネームまたは会社名", class: "form-control" %>
              <%= f.label :email %>
              <%= f.email_field :email, placeholder: "test@example.com", class: "form-control" %>
              <%= f.label :password %>
              <%= f.password_field :password, placeholder: "6文字以上のパスワード", class: 'form-control' %>
              <%= f.label :password_confirmation %>
              <%= f.password_field :password_confirmation, placeholder: "確認用パスワード", class: 'form-control' %>
              <%= f.submit 'Sign up', class: "btn btn-primary form-btn" %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<% provide :title, "マイページ" %>
<main>
  <div class="container">
    <%= render 'shared/flash' %>
    <%= render 'shared/error_messages', object: @user %>
    <div class="row">
      <div class="col-lg-3 col-md-12">
        <div class="mypage-box white-box">
          <div class="avatar-size-modify">
            <div class = "user-avatar">
              <%= render 'shared/avatar', avatar: @user.avatar %>
            </div>
          </div>
          <h2 class="user-name text-center"><%= @user.name %></h2>
          <% if current_user?(@user) %>
            <div class="link-form-user"><%= link_to "アカウント設定", edit_user_path(current_user) %></div>
          <% end %>
          <% if !(current_user?(@user)) && logged_in? %>
            <div id="follow_form<%= @user.id %>">
              <% if current_user.following?(@user) %>
                <%= render 'unfollow', user: @user %>
              <% else %>
                <%= render 'follow', user: @user %>
              <% end %>
            </div>
          <% end %>
          <% if current_user?(@user) %>
            <div class="link-form-user"><%= link_to "フォロー中:#{@user.following.size}", following_user_path(@user) %></div>
          <% end %>
          <% if @user.builder? %>
            <div class="builder-evaluate">
              <p class="text-center">評価</p>
              <div class="star-box">
                <% if @star.present? %>
                  <span class="star-number"><%= @star.average(:evaluation).round(1).to_f %></span>
                  <div class="stars"><%= render 'shared/stars', star_ave: @star.average(:evaluation).round(1).to_f %></div>
                <% else %>
                  <span class="star-number">0</span>
                  <div class="stars"><%= image_tag '0star.png' %></div>
                <% end %>
                <span><%= @star.blank? ? "まだ評価はありません" : (link_to_if logged_in?, "評価実績#{@star.size}件", reviews_path(params:{id: @user})) %></span>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-lg-9 col-md-12">
        <% if @user.builder? %>
          <div class="white-box">
            <h3 class="gray-bottom-line">会社概要</h3>
            <div class="profile-box">
              <% if @user.intro.present? %>
                <div class="intro"><%= safe_join(@user.intro.split("\n"),tag(:br)) %></div>
              <% else %>
                <div class="gray-color intro">アカウント設定から会社概要を設定してください。</div>
              <% end %>
            </div>
            <div class="flex profile-box">
              <% if @user.website.present? %>
                <div class="intro">会社URL：</div>
                <div><%= link_to @user.website, @user.website %></div>
              <% end %>
            </div>
          </div>
        <% elsif @user.intro.present? %>
          <div class="white-box">
            <h3 class="gray-bottom-line">プロフィール</h3>
            <div class="intro"><%= safe_join(@user.intro.split("\n"),tag(:br)) %></div>
          </div>
        <% end %>
        <div class="white-box">
            <% if @projects.any? %>
              <h3 class="gray-bottom-line">
                <%= current_user?(@user) ? "あなた" : @user.name %><%= @user.builder? ? "が提案中のプロジェクト(#{@user.suggests.size})" : "のプロジェクト(#{@user.projects.size})" %>
              </h3>
              <%= render 'projects/posted_projects', projects: @projects %>
            <% else %>
              <p>まだ<%= @user.builder? ? "提案" : "プロジェクト" %>がありません。</p>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<main>
  <div class="container">
    <div class = "row justify-content-center">
      <div class = "col-md-9 col-sm-12 white-box" >
        <h2 class="gray-bottom-line"><%= @title %></h2>
        <%= will_paginate @users, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>
        <ul>
        <% @users.each do |user| %>
          <li class="flex follow-box">
            <div class="flex follow-box">
              <div class="follow-user-avatar">
                <%= render 'shared/avatar', avatar: user.avatar %>
              </div>
              <%= link_to user.name, user_path(user) %>
            </div>
            <div id="follow_form<%= user.id %>">
              <% if current_user.following?(user) %>
                <%= render 'unfollow', user: user %>
              <% else %>
                <%= render 'follow', user: user %>
              <% end %>
            </div>
          </li>
        <% end %>
        </ul>
        <%= will_paginate @users, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>
      </div>
    </div>
  </div>
</main>