config/routes.rb
Rails.application.routes.draw do
  root 'landing#home'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destory]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :password_changes, only: [:new, :create, :edit, :update]
  resources :projects, only: [:index, :new, :create, :show, :destroy] do
    resources :suggests, only: [:new, :create, :show, :edit, :update, :destroy]
  end
  resources :comments, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :accept_suggests, only: [:create, :show]
  resources :reviews, only: [:index, :new, :create, :show, :edit, :update]
  resources :email_changes, only: [:edit, :update]
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :photos, as: :photable, inverse_of: :photable, dependent: :destroy
  has_many :suggests, dependent: :destroy

  accepts_nested_attributes_for :photos

  validates :name, presence: true
  validates :user_id, presence: true
  validates :content, presence: true
  validates :budget, numericality: { only_integer: true }, length: { maximum: 10 }, presence: true
  validates :photos, length: { maximum: 5 }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include Shared::SuggestSupport

  before_action :logged_in_user, only: [:new, :create, :destroy]
  before_action :builder_not_create, only: [:new, :create]

  def index
    @projects = Project.all.includes(:user).paginate(page: params[:page], per_page: 9)
  end

  def new
    @project = current_user.projects.build
    @project.photos.build
  end

  def show
    @project = Project.find_by(id: params[:id])
    if @project.nil?
      flash[:warning] = "お探しのページは見つかりませんでした。"
      redirect_to root_url
    else
      @suggest = already_suggest(@project)
    end
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:success] = "プロジェクトが投稿されました。"
      redirect_to project_path(@project)
    else
      render 'new'
    end
  end

  def destroy
    project = current_user.projects.find_by(id: params[:id])
    if project.blank?
      flash[:danger] = "該当するプロジェクトが見つかりません。"
      redirect_to root_url
    else
      project.destroy
      flash[:success] = "プロジェクトが削除されました。"
      redirect_to current_user
    end
  end

  private

  def project_params
    params.require(:project).permit(:name,
                                    :content,
                                    :budget,
                                    photos_attributes: [:image]).merge(user_id: current_user.id)
  end

  def builder_not_create
    if current_user.builder?
      redirect_to current_user
      flash[:warning] = "ビルダーはプロジェクトを作成できません。"
    end
  end
end

app/views/projects/_posted_projects.html.erb
<ol class="projects">
  <% projects.each do |project| %>
    <li class="flex">
      <div class = "project-user-avatar">
        <%= render 'shared/avatar', avatar: project.user.avatar %>
      </div>
      <div class="wide-box">
        <div class="link-to-project gray-bottom-line hidden"><%= link_to project.name, project_path(project) %></div>
        <div class="projecter-and-posted-time">
          <div class="project-user hidden"><span class="min-media-display-non">発注者: </span><%= project.user.name %></div>
          <div class="project-posted">
            <%= "#{time_ago_in_words(project.created_at)}前" %>
          </div>
        </div>
      </div>
    </li>
  <% end %>
</ol>
<%= will_paginate projects, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>

app/views/projects/index.html.erb
<% provide :title, "プロジェクト一覧" %>
<main>
  <div class="container">
    <div class = "row white-box">
      <div class = "col-sm-12">
        <h2 class="gray-bottom-line">プロジェクト一覧</h2>
        <%= render 'posted_projects', projects: @projects %>
      </div>
    </div>
  </div>

app/views/projects/new.html.erb
<% provide(:title,"案件を投稿する")%>
<main>
  <div class="container">
    <div class = "row">
      <div class="col-md-12 white-box">
        <h2 class="gray-bottom-line">プロジェクトの作成</h2>
        <%= render 'shared/error_messages', object: @project %>
        <%= form_with(model: @project, local: true) do |f| %>
          <div class="preview-field flex">
            <div id="label-field">
              <%= f.label :"photos_attributes_0_image", class: "photo-label", id: "photo-label-0" do %>
                <p>クリックして画像をアップロード(最大5枚)</p>
              <% end %>
            </div>
          </div>
          <%= f.fields_for :photos do |photo| %>
            <%= render 'shared/photo_upload', { model_name: "project", photo: photo } %>
          <% end %>
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control", placeholder: "東京都世田谷区S邸, 佐藤邸...etc" %>
          <%= f.label :budget %>
          <%= f.text_field :budget, class: "form-control", placeholder: "予算", data: { autonumeric: { mDec: 0 } } %>
          <%= f.label :content %>
          <%= f.text_area :content, class: "form-control", placeholder: "大まかな家のイメージや絶対に譲れない部分など" %>
          <%= f.submit "プロジェクトを投稿する", class: "btn btn-primary center-btn" %>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/projects/show.html.erb
<% provide(:title,"#{@project.name}") %>
<main>
  <div class="container">
  <%= render 'shared/flash' %>
  <%= render 'shared/error_messages', object: @project %>
    <div class = "row white-box">
      <div class = "col-sm-12">
        <h2 class="gray-bottom-line"><%= @project.name %></h2>
        <div>
          <div class="flex contributer">
            <div class="project-avatar"><%= render 'shared/avatar', avatar: @project.user.avatar %></div>
            <div><%= link_to @project.user.name, user_path(@project.user), class: "project-user-link" %></div>
          </div>
          <div>
            <% if @project.photos.present? %>
              <ul class="show-photo-field">
                <% @project.photos.each do |photo| %>
                  <li class="show-photo-box"><%= image_tag photo.image.url %></li>
                <% end %>
              </ul>
            <%end %>
          </div>
          <div class="project-parts"><span class="font-weight-bold">予算: </span><%= "#{@project.budget.to_s(:delimited)}円" %></div>
          <div class="project-parts"><span class="font-weight-bold">クライアント要望詳細</span></div>
          <div class="project-document">
            <%= simple_format(@project.content) %>
          </div>
          <div class="project-btn">
            <% if current_user?(@project.user) %>
              <%= link_to "プロジェクトを削除する", @project,
                                                method: :delete,
                                                data: { confirm: "本当に削除してもよろしいですか？" },
                                                class: "btn btn-danger" %>
            <% elsif @suggest.present? %>
              <%= link_to "提案したプロジェクトにいく", project_suggest_path(@project.id, @suggest.id), class: "btn btn-warning" %>
            <% elsif current_user.builder? && !current_user?(@project.user)  %>
              <%= link_to "このプロジェクトに提案する", new_project_suggest_path(@project.id), class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class = "row white-box">
      <div class = "col-sm-12">
        <% if @project.suggests.present? %>
          <div class="gray-bottom-line suggests"><%= @project.suggests.size %>件の提案</div>
          <div>
            <% @project.suggests.includes(:user).each do |suggest| %>
              <div class="flex align-items-center suggest-parts">
                <div class="suggest-avatar"><%= render 'shared/avatar', avatar: suggest.user.avatar %></div>
                <div class="suggest-parts-user"><%= suggest.user.name %></div>
                <div class="suggest-parts-title"><%= link_to suggest.title, project_suggest_path(@project, suggest) %></div>
              </div>
            <% end %>
          </div>
        <% else %>
          <p>まだ提案はありません。</p>
        <% end %>
      </div>
    </div>
  </div>
</main>